#!/usr/bin/env bash
# Script that transfers a file from our client to a server

# Check if exactly 4 arguments are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Use scp to transfer the file to the user's home directory
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
