#!/usr/bin/env bash
# Script that transfers a file from our client to a server with scp

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
